export interface BountyItem {
  level: string;
  name: string;
  category: string;
}

export const bountyEquipment: BountyItem[] = [
  // 劍
  { level: "1A", name: "長劍", category: "劍" },
  { level: "1B", name: "闊劍", category: "劍" },
  { level: "2A", name: "突刺劍", category: "劍" },
  { level: "2B", name: "火舌劍", category: "劍" },
  { level: "3A", name: "麵包劍", category: "劍" },
  { level: "3B", name: "雙手劍", category: "劍" },
  { level: "4A", name: "雙刃長劍", category: "劍" },
  { level: "4B", name: "鎖刃劍", category: "劍" },
  { level: "5A", name: "格鬥劍", category: "劍" },
  { level: "5B", name: "長鍔劍", category: "劍" },
  { level: "6A", name: "豬牙劍", category: "劍" },
  { level: "6B", name: "雙刃闊劍", category: "劍" },
  // 斧
  { level: "1A", name: "手斧", category: "斧" },
  { level: "1B", name: "勇氣之斧", category: "斧" },
  { level: "2A", name: "寬手斧", category: "斧" },
  { level: "2B", name: "戰鬥手斧", category: "斧" },
  { level: "3A", name: "格鬥手斧", category: "斧" },
  { level: "3B", name: "鋼斧", category: "斧" },
  { level: "4A", name: "長戰斧", category: "斧" },
  { level: "4B", name: "雙刃斧", category: "斧" },
  { level: "5A", name: "鉤爪斧", category: "斧" },
  { level: "5B", name: "闊刃斧", category: "斧" },
  { level: "6A", name: "彎月大戰斧", category: "斧" },
  { level: "6B", name: "大型闊刃斧", category: "斧" },
  // 矛
  { level: "1A", name: "短矛", category: "矛" },
  { level: "1B", name: "攻城槍", category: "矛" },
  { level: "2A", name: "刺槍", category: "矛" },
  { level: "2B", name: "金屬槍", category: "矛" },
  { level: "3A", name: "長柄彎槍", category: "矛" },
  { level: "3B", name: "長柄尖槍", category: "矛" },
  { level: "4A", name: "穗槍", category: "矛" },
  { level: "4B", name: "雙叉戟", category: "矛" },
  { level: "5A", name: "護衛槍", category: "矛" },
  { level: "5B", name: "騎士槍", category: "矛" },
  { level: "6A", name: "大砍槍", category: "矛" },
  { level: "6B", name: "長尖槍", category: "矛" },
  // 弓
  { level: "1A", name: "輕型弓", category: "弓" },
  { level: "1B", name: "威力短弓", category: "弓" },
  { level: "2A", name: "短戰弓", category: "弓" },
  { level: "2B", name: "獵弓", category: "弓" },
  { level: "3A", name: "強弓", category: "弓" },
  { level: "3B", name: "格鬥弓", category: "弓" },
  { level: "4A", name: "狙擊弓", category: "弓" },
  { level: "4B", name: "超強狙擊弓", category: "弓" },
  { level: "5A", name: "殺手長弓", category: "弓" },
  { level: "5B", name: "衝擊弓", category: "弓" },
  { level: "6A", name: "巨弓", category: "弓" },
  { level: "6B", name: "長格鬥弓", category: "弓" },
  // 杖
  { level: "1A", name: "短杖", category: "杖" },
  { level: "1B", name: "權杖", category: "杖" },
  { level: "2A", name: "大地之杖", category: "杖" },
  { level: "2B", name: "激流權杖", category: "杖" },
  { level: "3A", name: "魔之手杖", category: "杖" },
  { level: "3B", name: "魔之權杖", category: "杖" },
  { level: "4A", name: "賢者手杖", category: "杖" },
  { level: "4B", name: "賢者權杖", category: "杖" },
  { level: "5A", name: "琥珀杖", category: "杖" },
  { level: "5B", name: "琥珀權杖", category: "杖" },
  { level: "6A", name: "元素之杖", category: "杖" },
  { level: "6B", name: "神聖之杖", category: "杖" },
  // 小刀
  { level: "1A", name: "小刀", category: "小刀" },
  { level: "1B", name: "銳刃小刀", category: "小刀" },
  { level: "2A", name: "圓盤小刀", category: "小刀" },
  { level: "2B", name: "細刃擲刀", category: "小刀" },
  { level: "3A", name: "滑翔小刀", category: "小刀" },
  { level: "3B", name: "細直刃小刀", category: "小刀" },
  { level: "4A", name: "耳柄小刀", category: "小刀" },
  { level: "4B", name: "騎士小刀", category: "小刀" },
  { level: "5A", name: "球鍔小刀", category: "小刀" },
  { level: "5B", name: "雙刃小刀", category: "小刀" },
  { level: "6A", name: "闊刃小刀", category: "小刀" },
  { level: "6B", name: "觸角小刀", category: "小刀" },
  // 回力鏢
  { level: "1A", name: "木製大型回力鏢", category: "回力鏢" },
  { level: "1B", name: "青銅回力鏢", category: "回力鏢" },
  { level: "2A", name: "追跡者", category: "回力鏢" },
  { level: "2B", name: "彩光回力鏢", category: "回力鏢" },
  { level: "3A", name: "暗殺回力鏢", category: "回力鏢" },
  { level: "3B", name: "殺敵回力鏢", category: "回力鏢" },
  { level: "4A", name: "獅子回力鏢", category: "回力鏢" },
  { level: "4B", name: "銳角回力鏢", category: "回力鏢" },
  { level: "5A", name: "翼鹿回力鏢", category: "回力鏢" },
  { level: "5B", name: "阿修塔羅回力鏢", category: "回力鏢" },
  { level: "6A", name: "蛇獅回力鏢", category: "回力鏢" },
  { level: "6B", name: "鶇回力鏢", category: "回力鏢" },
  // 頭盔
  { level: "1A", name: "硬皮頭盔", category: "頭盔" },
  { level: "1B", name: "銅製頭盔", category: "頭盔" },
  { level: "2A", name: "鐵板布盔", category: "頭盔" },
  { level: "2B", name: "銅鐵皮盔", category: "頭盔" },
  { level: "3A", name: "金屬護額", category: "頭盔" },
  { level: "3B", name: "鐵製頭盔", category: "頭盔" },
  { level: "4A", name: "霸葛頭盔", category: "頭盔" },
  { level: "4B", name: "角飾頭盔", category: "頭盔" },
  { level: "5A", name: "開放式頭盔", category: "頭盔" },
  { level: "5B", name: "葛理克頭盔", category: "頭盔" },
  { level: "6A", name: "巴比克頭盔", category: "頭盔" },
  { level: "6B", name: "利刃頭盔", category: "頭盔" },
  // 帽子
  { level: "1A", name: "麻布帽", category: "帽子" },
  { level: "1B", name: "硬帽", category: "帽子" },
  { level: "2A", name: "輕帽", category: "帽子" },
  { level: "2B", name: "皮帽", category: "帽子" },
  { level: "3A", name: "硬皮帽", category: "帽子" },
  { level: "3B", name: "可愛的帽子", category: "帽子" },
  { level: "4A", name: "時髦帽子", category: "帽子" },
  { level: "4B", name: "鴨舌帽", category: "帽子" },
  { level: "5A", name: "藍徽章之帽", category: "帽子" },
  { level: "5B", name: "高級帽子", category: "帽子" },
  { level: "6A", name: "裝飾著花的帽子", category: "帽子" },
  { level: "6B", name: "青銅帽子", category: "帽子" },
  // 鎧甲
  { level: "1A", name: "軟皮甲", category: "鎧甲" },
  { level: "1B", name: "護心甲", category: "鎧甲" },
  { level: "2A", name: "青銅鎧甲", category: "鎧甲" },
  { level: "2B", name: "輕型鎧甲", category: "鎧甲" },
  { level: "3A", name: "輕型鎖鍊甲", category: "鎧甲" },
  { level: "3B", name: "環甲", category: "鎧甲" },
  { level: "4A", name: "鋼鐵鎧甲", category: "鎧甲" },
  { level: "4B", name: "金屬皮甲", category: "鎧甲" },
  { level: "5A", name: "長型金屬鎧甲", category: "鎧甲" },
  { level: "5B", name: "索狀鎧甲", category: "鎧甲" },
  { level: "6A", name: "重鐵板甲", category: "鎧甲" },
  { level: "6B", name: "鐵板半身甲", category: "鎧甲" },
  // 衣服
  { level: "1A", name: "旅人之服", category: "衣服" },
  { level: "1B", name: "保護衣", category: "衣服" },
  { level: "2A", name: "羽毛裝", category: "衣服" },
  { level: "2B", name: "皮裝", category: "衣服" },
  { level: "3A", name: "硬皮服", category: "衣服" },
  { level: "3B", name: "鎖鏈裝", category: "衣服" },
  { level: "4A", name: "布甲", category: "衣服" },
  { level: "4B", name: "襯甲", category: "衣服" },
  { level: "5A", name: "環服", category: "衣服" },
  { level: "5B", name: "士兵護衣", category: "衣服" },
  { level: "6A", name: "長索錐衣", category: "衣服" },
  { level: "6B", name: "索錐上衣", category: "衣服" },
  // 袍
  { level: "1A", name: "羽毛袍", category: "袍" },
  { level: "1B", name: "輕皮袍", category: "袍" },
  { level: "2A", name: "網袍", category: "袍" },
  { level: "2B", name: "風袍", category: "袍" },
  { level: "3A", name: "硬皮袍", category: "袍" },
  { level: "3B", name: "環袍", category: "袍" },
  { level: "4A", name: "烏鴉之袍", category: "袍" },
  { level: "4B", name: "月亮之袍", category: "袍" },
  { level: "4C", name: "狐皮披風", category: "袍" },
  { level: "5A", name: "東方法衣", category: "袍" },
  { level: "5B", name: "聖堂之袍", category: "袍" },
  { level: "6A", name: "聖者之袍", category: "袍" },
  { level: "6B", name: "戰鬥長袍", category: "袍" },
  // 靴子
  { level: "1A", name: "軟皮靴", category: "靴子" },
  { level: "1B", name: "皮靴", category: "靴子" },
  { level: "2A", name: "硬皮靴", category: "靴子" },
  { level: "2B", name: "長靴", category: "靴子" },
  { level: "3A", name: "厚底靴", category: "靴子" },
  { level: "3B", name: "編織的靴子", category: "靴子" },
  { level: "4A", name: "鎖鍊長靴", category: "靴子" },
  { level: "4B", name: "鎖鍊靴", category: "靴子" },
  { level: "5A", name: "蜥蝪靴", category: "靴子" },
  { level: "5B", name: "蜥蝪長靴", category: "靴子" },
  { level: "6A", name: "鋼靴", category: "靴子" },
  { level: "6B", name: "鋼製長靴", category: "靴子" },
  // 鞋
  { level: "1A", name: "運動鞋", category: "鞋" },
  { level: "1B", name: "馬車鞋", category: "鞋" },
  { level: "2A", name: "皮鞋", category: "鞋" },
  { level: "2B", name: "安全鞋", category: "鞋" },
  { level: "3A", name: "光之鞋", category: "鞋" },
  { level: "3B", name: "戰鞋", category: "鞋" },
  { level: "4A", name: "薄板鞋", category: "鞋" },
  { level: "4B", name: "鎖鏈鞋", category: "鞋" },
  { level: "5A", name: "蜥蝪鞋", category: "鞋" },
  { level: "5B", name: "維京鞋", category: "鞋" },
  { level: "6A", name: "戰鬥鞋", category: "鞋" },
  { level: "6B", name: "騎士鞋", category: "鞋" },
  // 盾
  { level: "1A", name: "小圓盾", category: "盾" },
  { level: "1B", name: "小型盾", category: "盾" },
  { level: "2A", name: "板盾", category: "盾" },
  { level: "2B", name: "鳶盾", category: "盾" },
  { level: "3A", name: "漩渦重盾", category: "盾" },
  { level: "3B", name: "哥特盾", category: "盾" },
  { level: "4A", name: "士兵盾", category: "盾" },
  { level: "4B", name: "重盾", category: "盾" },
  { level: "5A", name: "蜥蝪盾", category: "盾" },
  { level: "5B", name: "反光之盾", category: "盾" },
  { level: "6A", name: "風之盾", category: "盾" },
  { level: "6B", name: "獅子盾", category: "盾" },
];

export const bountyPets: string[] = [
  "大地鼠",
  "迷你蝙蝠",
  "哥布林",
  "紅帽哥布林",
  "樹精",
  "妖草",
  "異型蜂",
  "惡魔螃蟹",
  "穴熊",
  "大蝙蝠",
  "火蜘蛛",
  "火焰鼠",
  "小惡魔",
  "蜥蜴戰士",
  "印地安仙人掌",
  "殺手蠍",
  "紅蠍",
  "火焰哥布林",
  "烈風哥布林",
  "蔓陀羅草",
  "幻歌妖",
  "烈風鳥人",
  "胖蝙蝠",
  "死亡蜂",
  "死亡樹精",
  "殺人蜂"
];

// 按類別分組懸賞裝備
export function groupBountyEquipmentByCategory(): Record<string, BountyItem[]> {
  const grouped: Record<string, BountyItem[]> = {};
  
  for (const item of bountyEquipment) {
    if (!grouped[item.category]) {
      grouped[item.category] = [];
    }
    grouped[item.category].push(item);
  }
  
  return grouped;
}
