// Generated by wxt
export {}
declare global {
  const API_CONFIG: typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/constants').API_CONFIG
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const ERROR_MESSAGES: typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/constants').ERROR_MESSAGES
  const EffectScope: typeof import('vue').EffectScope
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const MARKET_CONFIG: typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/constants').MARKET_CONFIG
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const SUCCESS_MESSAGES: typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/constants').SUCCESS_MESSAGES
  const bountyEquipment: typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/bountyData').bountyEquipment
  const bountyPets: typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/bountyData').bountyPets
  const browser: typeof import('wxt/browser').browser
  const clearStorage: typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/storage').clearStorage
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const customRef: typeof import('vue').customRef
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineComponent: typeof import('vue').defineComponent
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const effectScope: typeof import('vue').effectScope
  const extractCdKey: typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/api').extractCdKey
  const extractStallCoordinates: typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/api').extractStallCoordinates
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const fetchAllMarketPages: typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/api').fetchAllMarketPages
  const fetchMarketData: typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/api').fetchMarketData
  const fetchMarketHistory: typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/api').fetchMarketHistory
  const filterMarketDataBySearch: typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/api').filterMarketDataBySearch
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getExtensionUrl: typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/messaging').getExtensionUrl
  const getSettings: typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/storage').getSettings
  const getStorage: typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/storage').getStorage
  const getTimeUntilExpiration: typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/api').getTimeUntilExpiration
  const groupBountyEquipmentByCategory: typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/bountyData').groupBountyEquipmentByCategory
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMessage: typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/messaging').onMessage
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const removeStorage: typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/storage').removeStorage
  const resolveComponent: typeof import('vue').resolveComponent
  const sendMessage: typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/messaging').sendMessage
  const setSettings: typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/storage').setSettings
  const setStorage: typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/storage').setStorage
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const storage: typeof import('wxt/utils/storage').storage
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const updateSetting: typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/storage').updateSetting
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
  const useAttrs: typeof import('vue').useAttrs
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useId: typeof import('vue').useId
  const useModel: typeof import('vue').useModel
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { BountyItem } from 'C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/bountyData'
  import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/bountyData')
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface ComponentCustomProperties {
    readonly API_CONFIG: UnwrapRef<typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/constants')['API_CONFIG']>
    readonly ContentScriptContext: UnwrapRef<typeof import('wxt/utils/content-script-context')['ContentScriptContext']>
    readonly ERROR_MESSAGES: UnwrapRef<typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/constants')['ERROR_MESSAGES']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly InvalidMatchPattern: UnwrapRef<typeof import('wxt/utils/match-patterns')['InvalidMatchPattern']>
    readonly MARKET_CONFIG: UnwrapRef<typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/constants')['MARKET_CONFIG']>
    readonly MatchPattern: UnwrapRef<typeof import('wxt/utils/match-patterns')['MatchPattern']>
    readonly SUCCESS_MESSAGES: UnwrapRef<typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/constants')['SUCCESS_MESSAGES']>
    readonly bountyEquipment: UnwrapRef<typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/bountyData')['bountyEquipment']>
    readonly bountyPets: UnwrapRef<typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/bountyData')['bountyPets']>
    readonly browser: UnwrapRef<typeof import('wxt/browser')['browser']>
    readonly clearStorage: UnwrapRef<typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/storage')['clearStorage']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createIframeUi: UnwrapRef<typeof import('wxt/utils/content-script-ui/iframe')['createIframeUi']>
    readonly createIntegratedUi: UnwrapRef<typeof import('wxt/utils/content-script-ui/integrated')['createIntegratedUi']>
    readonly createShadowRootUi: UnwrapRef<typeof import('wxt/utils/content-script-ui/shadow-root')['createShadowRootUi']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAppConfig: UnwrapRef<typeof import('wxt/utils/define-app-config')['defineAppConfig']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineBackground: UnwrapRef<typeof import('wxt/utils/define-background')['defineBackground']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineContentScript: UnwrapRef<typeof import('wxt/utils/define-content-script')['defineContentScript']>
    readonly defineUnlistedScript: UnwrapRef<typeof import('wxt/utils/define-unlisted-script')['defineUnlistedScript']>
    readonly defineWxtPlugin: UnwrapRef<typeof import('wxt/utils/define-wxt-plugin')['defineWxtPlugin']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly extractCdKey: UnwrapRef<typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/api')['extractCdKey']>
    readonly extractStallCoordinates: UnwrapRef<typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/api')['extractStallCoordinates']>
    readonly fakeBrowser: UnwrapRef<typeof import('wxt/testing')['fakeBrowser']>
    readonly fetchAllMarketPages: UnwrapRef<typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/api')['fetchAllMarketPages']>
    readonly fetchMarketData: UnwrapRef<typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/api')['fetchMarketData']>
    readonly fetchMarketHistory: UnwrapRef<typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/api')['fetchMarketHistory']>
    readonly filterMarketDataBySearch: UnwrapRef<typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/api')['filterMarketDataBySearch']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly getExtensionUrl: UnwrapRef<typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/messaging')['getExtensionUrl']>
    readonly getSettings: UnwrapRef<typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/storage')['getSettings']>
    readonly getStorage: UnwrapRef<typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/storage')['getStorage']>
    readonly getTimeUntilExpiration: UnwrapRef<typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/api')['getTimeUntilExpiration']>
    readonly groupBountyEquipmentByCategory: UnwrapRef<typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/bountyData')['groupBountyEquipmentByCategory']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly injectScript: UnwrapRef<typeof import('wxt/utils/inject-script')['injectScript']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMessage: UnwrapRef<typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/messaging')['onMessage']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly removeStorage: UnwrapRef<typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/storage')['removeStorage']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly sendMessage: UnwrapRef<typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/messaging')['sendMessage']>
    readonly setSettings: UnwrapRef<typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/storage')['setSettings']>
    readonly setStorage: UnwrapRef<typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/storage')['setStorage']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly storage: UnwrapRef<typeof import('wxt/utils/storage')['storage']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly updateSetting: UnwrapRef<typeof import('C:/Users/sacre/Documents/GitHub/StarCG-Market-Extension/extension/utils/storage')['updateSetting']>
    readonly useAppConfig: UnwrapRef<typeof import('wxt/utils/app-config')['useAppConfig']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}
